### ISSUE TITLE
can-define-validate-validatejs demo is not working

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-define-validate-validatejs#16]
@pYr0x commented on [Tue May 23 2017](https://github.com/canjs/canjs/issues/3274)

the demo is not working. http://canjs.com/doc/can-define-validate-validatejs.html

```"Error loading "validate.js@0.11.1#validate" at http://canjs.com/node_modules/validate.js/validate.js
Error loading "validate.js@0.11.1#validate" from "undefined" at <unknown>
Not Found: http://canjs.com/node_modules/validate.js/validate/index.js" undefined```

**Comment by Macrofig** [comment]
When was the last time we deployed the site? This issue was fixed here: https://github.com/canjs/canjs/pull/3191

**Comment by chasenlehara** [comment]
That fix doesn’t look right to me; I think you need to include `node_modules/validate.js` so the package’s files are deployed as well.

**Comment by Macrofig** [comment]
@chasenlehara So instead of `git add -f node_modules/validate.js/package.json` I should have `git add -f node_modules/validate.js`?

**Comment by chasenlehara** [comment]
I _think_ so.

**Comment by Macrofig** [comment]
@justinbmeyer @phillipskevin Can you confirm the fix?

**Comment by justinbmeyer** [comment]
yes, if that adds everything in the `validate.js` folder
