### ISSUE TITLE
Dependency mismatch for can-validate-validatejs

### ISSUE THREAD

**Issue by rjgotten** [canjs/can-define-validate-validatejs#64]
`npm ls can-validate-validatejs` gives me (for CanJS 5.33.2 - but this will be no different for later versions, as 1.1.1 is the latest for the `can-define-validate-validatejs` package):

```
`-- can@5.33.2
  +-- can-define-validate-validatejs@1.1.1
  | `-- can-validate-validatejs@0.1.3 
  `-- can-validate-validatejs@1.0.1
```

i.e. `can-define-validate-validatejs` is using a version range that is not compatible with the top-level `can` package and is leading to a duplicated local copy of the older dependency. This is in fact complicating a local workaround for _another_ issue reported on `can-validate-validatejs`, freshly reported: https://github.com/canjs/can-validate-validatejs/issues/44

I now have to concoct a build-step workaround which somehow swaps out _both_ packages with fixed versions.

**Comment by rjgotten** [comment]
Literally the only line difference for `can-validate-validatejs` sofar (with aforementioned issue untreated) appears to be a "use strict" directive. Can you please just bump the dependency from the 0.1.x range into the 1.0.x range and publish a 1.1.2 version of the `can-define-validate-validatejs` package?

That should still fit version constraints, even for the 5.x range of the main `can` package.

**Comment by justinbmeyer** [comment]
Yeah, we can look into this. Thanks!
